name: fabric-storyboard-copilot
metadata:
  template: fabric-storyboard-copilot
services:
  web:
    project: .
    language: ts
    host: staticwebapp
    dist: dist
    hooks:
      prebuild:
        run: npm ci && cd api && npm ci
      build:
        run: npm run build && cd api && npm run build
infra:
  provider: bicep
  path: infra
  module: main
